In [4]:
import polars as pl
df = pl.read_csv(
    source = "/home/hungpham/DE_Project_Exam/platforms/ingestion/source_data/de_assessment_data.csv"
)

In [5]:
df.head()

shape: (5, 14)
┌────────────┬────────────┬───────────┬─────────┬───┬────────┬───────────┬────────────┬────────────┐
│ event_id   ┆ event_time ┆ entity_id ┆ zone_id ┆ … ┆ value  ┆ sub_value ┆ total_valu ┆ payment_me │
│ ---        ┆ stamp      ┆ ---       ┆ ---     ┆   ┆ ---    ┆ ---       ┆ e          ┆ thod       │
│ str        ┆ ---        ┆ i64       ┆ i64     ┆   ┆ f64    ┆ f64       ┆ ---        ┆ ---        │
│            ┆ str        ┆           ┆         ┆   ┆        ┆           ┆ f64        ┆ str        │
╞════════════╪════════════╪═══════════╪═════════╪═══╪════════╪═══════════╪════════════╪════════════╡
│ bdd640fb-0 ┆ 2024-10-01 ┆ 2568      ┆ 241     ┆ … ┆ 71.05  ┆ 12.86     ┆ 83.91      ┆ card       │
│ 667-1ad1-1 ┆ 00:00:10   ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ c80-317fa3 ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ …          ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ 23b8c1e9-3 ┆ 2024-10-01 ┆ 2320      ┆ 225     ┆ … ┆ 40.33  ┆ 0.0       ┆ 40.33      ┆ cash       │
│ 924-56de-3 ┆ 00:01:28   ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ eb1-3b9046 ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ …          ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ bd9c66b3-a ┆ 2024-10-01 ┆ 384       ┆ 129     ┆ … ┆ 49.69  ┆ 5.09      ┆ 54.78      ┆ card       │
│ d3c-2d6d-1 ┆ 00:02:26   ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ a3d-1fa7bc ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ …          ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ 972a8469-1 ┆ 2024-10-01 ┆ 253       ┆ 177     ┆ … ┆ 146.19 ┆ 26.3      ┆ 172.49     ┆ card       │
│ 641-9f82-8 ┆ 00:03:38   ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ b9d-2434e4 ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ …          ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ 17fc695a-0 ┆ 2024-10-01 ┆ 1041      ┆ 236     ┆ … ┆ 135.68 ┆ 19.4      ┆ 155.08     ┆ card       │
│ 7a0-ca6e-0 ┆ 00:04:55   ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ 822-e8f36c ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
│ …          ┆            ┆           ┆         ┆   ┆        ┆           ┆            ┆            │
└────────────┴────────────┴───────────┴─────────┴───┴────────┴───────────┴────────────┴────────────┘

In [6]:
df.describe()

shape: (9, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ event_id  ┆ event_tim ┆ entity_id ┆ … ┆ value     ┆ sub_value ┆ total_val ┆ payment_ │
│ ---       ┆ ---       ┆ estamp    ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ue        ┆ method   │
│ str       ┆ str       ┆ ---       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ f64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 287924    ┆ 287924    ┆ 287924.0  ┆ … ┆ 287924.0  ┆ 287924.0  ┆ 287924.0  ┆ 287924   │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 1502.6150 ┆ … ┆ 42.273547 ┆ 3.410957  ┆ 46.19794  ┆ null     │
│           ┆           ┆           ┆ 41        ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ 864.66714 ┆ … ┆ 33.856379 ┆ 4.530328  ┆ 36.789707 ┆ null     │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 00001750- ┆ 2024-10-0 ┆ 1.0       ┆ … ┆ -350.0    ┆ 0.0       ┆ -364.73   ┆ account  │
│           ┆ 0ce3-5486 ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ -517d-046 ┆ 00:00:10  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6cb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 754.0     ┆ … ┆ 21.38     ┆ 0.59      ┆ 23.54     ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ 1504.0    ┆ … ┆ 32.89     ┆ 2.11      ┆ 36.06     ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ 2250.0    ┆ … ┆ 52.11     ┆ 4.49      ┆ 56.95     ┆ null     │
│ max       ┆ ffffe1a7- ┆ 2024-12-3 ┆ 3000.0    ┆ … ┆ 350.0     ┆ 109.04    ┆ 459.04    ┆ voucher  │
│           ┆ 8000-2164 ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ -04aa-b88 ┆ 23:59:52  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0e1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
df["event_type"].unique()

shape: (5,)
Series: 'event_type' [str]
[
	"bulk"
	"standard"
	"express"
	"scheduled"
	"premium"
]

In [8]:
df["rate_type"].unique()

shape: (6,)
Series: 'rate_type' [i64]
[
	1
	2
	3
	4
	5
	6
]

In [9]:
df["payment_method"].unique()

shape: (4,)
Series: 'payment_method' [str]
[
	"account"
	"card"
	"voucher"
	"cash"
]

In [ ]:
Với các thông tin này thì có thể thấy đây là thông tin về giao hàng hoặc chở khách,
Mỗi hàng là một chuyến đi (trip event) đã hoàn thành trong Q4 2024, là 1 dòng grant dữ liệu.
Đây là dữ liệu append-only fact — một event đã xảy ra thì không bao giờ thay đổi về mặt nghiệp vụ. 
Nhận diện dựa trên: zone_id, destination_id, passenger_count, duration, vendor_id, entity_id (driver/vehicle).

Từ dòng grant này thì sẽ có thể tách ra thành các bảng như sau:
1 là entity_table:
2 là location_table
3 là rate
4 là vendor
5 là trip